FROM python:3.6 as remme-token-bot-runtime

WORKDIR gimmeremmetokensbot

COPY gimmeremmetokensbot .
COPY requirements.txt .
COPY requirements-production.txt .

RUN apt-get update && \
    apt-get install libsecp256k1-dev -y && \
    pip3 install -r requirements.txt && \
    pip3 install -r requirements-production.txt

CMD ["/bin/bash", "./scripts/deployment/heroku.sh"]
